### ISSUE TITLE
can't run the wrapper

### ISSUE THREAD

**Issue by maciejbrylewicz** [cagatayuresin/odoo-xmlrpc-wrapper#3]
see the details below:

Exception has occurred: AttributeError
'Bot' object has no attribute 'status'
  File "/home/maciej/devel/odoo_xmlrpc/from odoo_xmlrpc_wrapper import odoo_xml.py", line 9, in <module>
    bot = oxw.Bot(HOST, DB, USERLOGIN, PASSWORD)
AttributeError: 'Bot' object has no attribute 'status'

Maybe there is something missing for v16?

**Comment by hidara2000** [comment]
make the changes below to `.........\lib\site-packages\odoo_xmlrpc_wrapper\odoo_xmlrpc_wrapper.py`
![image](https://github.com/cagatayuresin/odoo-xmlrpc-wrapper/assets/15170494/2e1feffd-1803-4513-b8a9-ee3e85c457c2)

**Comment by ddean6232** [comment]
anything??  

Traceback (most recent call last):
  File "C:\Users\darren_dean\Projects\python\odoo\test.py", line 9, in <module>
    bot = oxw.Bot(HOST, DB, USERLOGIN, PASSWORD, secured=False)
  File "C:\Users\darren_dean\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\odoo_xmlrpc_wrapper\odoo_xmlrpc_wrapper.py", line 58, in __init__
    print(self.status)
AttributeError: 'Bot' object has no attribute 'status'. Did you mean: 'satus'?

```
from odoo_xmlrpc_wrapper import odoo_xmlrpc_wrapper as oxw


HOST = "192.xxx.0.xx:8069"
DB = "odoo"
USERLOGIN = "ddean@dtreeind.com"
PASSWORD = "xxxxxxxxx"

bot = oxw.Bot(HOST, DB, USERLOGIN, PASSWORD, secured=False)

```

**Comment by cagatayuresin** [comment]
Thanks for the report. This was caused by the older package's `satus` / `status` typo during initialization, rather than an Odoo 16 compatibility requirement.

The current source fixes the typo, removes automatic printing during construction, and includes regression tests for initialization and `status()`. Connection details are now available explicitly with:

```python
print(bot.status())
```

The fix is on `master`. At the time of this reply, PyPI still serves **1.1.1** and **2.0.0 has not been published**, so upgrading from PyPI alone will not pick up the current changes. To try the verified source snapshot now, use **Python 3.10+** and install it in your project environment:

```bash
python -m pip install --upgrade "git+https://github.com/cagatayuresin/odoo-xmlrpc-wrapper.git@8343e1da3a79779d125f4350a10e31299987863f"
```

This installs a GitHub source snapshot of the upcoming major release. Please review the [2.0.0 migration notes](https://github.com/cagatayuresin/odoo-xmlrpc-wrapper/blob/8343e1da3a79779d125f4350a10e31299987863f/CHANGELOG.md#migration-from-111), including the Python requirement and changed return values.

Closing as fixed in source; the PyPI release is pending. If the same exception occurs with this snapshot, please open a new issue with the Python version, installed package version, and traceback, without credentials.
